sonar.projectKey=unity-multiplayer-game
sonar.projectName=DevProject
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=Assets/Network_Game,scripts,supabase
sonar.inclusions=Assets/Network_Game/**/*.cs,supabase/functions/**/*.ts,scripts/**/*.py
sonar.exclusions=**/Library/**,**/Temp/**,**/.git/**,**/node_modules/**,**/*.meta,**/*.png,**/*.jpg
sonar.test.inclusions=**/*Test*.cs,**/*Tests*.cs

sonar.host.url=http://localhost:9000
sonar.java.binaries=bin